CREATE TABLE "NotificationChannel" ("id" TEXT NOT NULL, "memberId" TEXT NOT NULL, "provider" TEXT NOT NULL, "externalUserId" TEXT NOT NULL, "externalChatId" TEXT, "isVerified" BOOLEAN NOT NULL DEFAULT false, "isEnabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NotificationChannel_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NotificationPreference" ("id" TEXT NOT NULL, "memberId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "telegramEnabled" BOOLEAN NOT NULL DEFAULT true, "baleEnabled" BOOLEAN NOT NULL DEFAULT true, "inAppEnabled" BOOLEAN NOT NULL DEFAULT true, "quietHoursEnabled" BOOLEAN NOT NULL DEFAULT false, "quietHoursStart" TEXT, "quietHoursEnd" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NotificationPreference_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NotificationOutbox" ("id" TEXT NOT NULL, "eventType" TEXT NOT NULL, "aggregateType" TEXT NOT NULL, "aggregateId" TEXT NOT NULL, "memberId" TEXT NOT NULL, "provider" TEXT NOT NULL, "recipientId" TEXT NOT NULL, "payload" JSONB NOT NULL, "idempotencyKey" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "attemptCount" INTEGER NOT NULL DEFAULT 0, "nextAttemptAt" TIMESTAMP(3), "sentAt" TIMESTAMP(3), "failedAt" TIMESTAMP(3), "lastError" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NotificationOutbox_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NotificationLog" ("id" TEXT NOT NULL, "outboxId" TEXT, "provider" TEXT NOT NULL, "recipientId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "status" TEXT NOT NULL, "providerMessageId" TEXT, "errorCode" TEXT, "errorMessage" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "NotificationLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AccountLinkCode" ("id" TEXT NOT NULL, "memberId" TEXT NOT NULL, "provider" TEXT NOT NULL, "codeHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdByIp" TEXT, "attemptCount" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "AccountLinkCode_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProcessedProviderUpdate" ("id" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerUpdateId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProcessedProviderUpdate_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "NotificationChannel_provider_externalUserId_key" ON "NotificationChannel"("provider", "externalUserId");
CREATE UNIQUE INDEX "NotificationChannel_memberId_provider_key" ON "NotificationChannel"("memberId", "provider");
CREATE INDEX "NotificationChannel_memberId_provider_idx" ON "NotificationChannel"("memberId", "provider");
CREATE UNIQUE INDEX "NotificationPreference_memberId_eventType_key" ON "NotificationPreference"("memberId", "eventType");
CREATE UNIQUE INDEX "NotificationOutbox_idempotencyKey_key" ON "NotificationOutbox"("idempotencyKey");
CREATE INDEX "NotificationOutbox_status_nextAttemptAt_idx" ON "NotificationOutbox"("status", "nextAttemptAt");
CREATE INDEX "NotificationOutbox_memberId_createdAt_idx" ON "NotificationOutbox"("memberId", "createdAt");
CREATE INDEX "NotificationLog_provider_recipientId_createdAt_idx" ON "NotificationLog"("provider", "recipientId", "createdAt");
CREATE INDEX "NotificationLog_outboxId_idx" ON "NotificationLog"("outboxId");
CREATE UNIQUE INDEX "AccountLinkCode_codeHash_key" ON "AccountLinkCode"("codeHash");
CREATE INDEX "AccountLinkCode_memberId_provider_createdAt_idx" ON "AccountLinkCode"("memberId", "provider", "createdAt");
CREATE INDEX "AccountLinkCode_expiresAt_idx" ON "AccountLinkCode"("expiresAt");
CREATE UNIQUE INDEX "ProcessedProviderUpdate_provider_providerUpdateId_key" ON "ProcessedProviderUpdate"("provider", "providerUpdateId");
CREATE INDEX "ProcessedProviderUpdate_createdAt_idx" ON "ProcessedProviderUpdate"("createdAt");
ALTER TABLE "NotificationChannel" ADD CONSTRAINT "NotificationChannel_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationOutbox" ADD CONSTRAINT "NotificationOutbox_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationLog" ADD CONSTRAINT "NotificationLog_outboxId_fkey" FOREIGN KEY ("outboxId") REFERENCES "NotificationOutbox"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AccountLinkCode" ADD CONSTRAINT "AccountLinkCode_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE CASCADE ON UPDATE CASCADE;
