module.exports = {
  apps: [
    {
      name: "taskmanager",
      script: ".next/standalone/server.js",
      interpreter: "node",
      node_args: "--env-file=.env",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: "8502",
        HOSTNAME: "0.0.0.0",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: "8502",
        HOSTNAME: "0.0.0.0",
      },
    },
    {
      name: "taskmanager-notification-worker",
      script: "./node_modules/tsx/dist/cli.mjs",
      args: "scripts/notification-worker.ts",
      interpreter: "node",
      node_args: "--env-file=.env",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: { NODE_ENV: "production" },
      env_production: { NODE_ENV: "production" },
    },
    {
      name: "taskmanager-bale-command-worker",
      script: "./node_modules/tsx/dist/cli.mjs",
      args: "scripts/bale-command-worker.ts",
      interpreter: "node",
      node_args: "--env-file=.env",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: { NODE_ENV: "production" },
      env_production: { NODE_ENV: "production" },
    },
  ],
};
